<a href="https://colab.research.google.com/github/Prajwal-ak-0/AI/blob/master/Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to Machine Learning and Deep Learning

**Machine Learning (ML)**: A branch of AI that learns from data and predicts unseen data. It can be applied everywhere, as long as we are able to convert the data into numbers, program it, and find patterns.

### Differences between ML and DL
* **Machine Learning (ML)** is generally applied to structured data.
* **Deep Learning (DL)**, a subset of ML, is typically applied to unstructured data.

### When to Apply ML/DL
* When we cannot specify all the rules we are going to encounter and the environment keeps changing with time.
* When there is a large amount of data, we can use ML/DL to gain insights.

### When Not to Apply DL
* If we can solve the problem with simple ML, it is better to avoid DL as it requires more computation.
* In the absence of large data, ML is preferred to deliver accurate results.

![Machine Learning vs Deep Learning](https://assets-global.website-files.com/5fb24a974499e90dae242d98/60f6fcbbeb0b8f57a7980a98_5f213db7c7763a9288759ad1_5eac2d0ef117c236e34cc0ff_DeepLearning.jpeg)

# Artificial Neural Network (ANN)

**Artificial Neural Network (ANN)**: A model inspired by the structure and function of biological neural networks. It consists of:

1. **Input Layer**: The incoming data is fed into this layer. Generally, it is a single layer.
2. **Hidden Layer(s)**: The model can consist of any number of hidden layers. Each layer helps in feature extraction.
3. **Output Layer**: Based on the extracted features, this layer makes the final decision.




# 2. Tensorflow basics

**TensorFlow**: An end-to-end open-source machine learning platform used to develop models for various tasks, including natural language processing, image recognition, etc.

* Contains prebuilt models.
* Provides the tools to build or customize a model.


In [1]:
import tensorflow as tf

In [2]:
scalar = tf.constant(10)
scalar
print(scalar.ndim)

0


In [3]:
vector = tf.constant([10,20,30,40])
vector
print(vector.ndim)

1


In [4]:
matrix = tf.constant([[10,20,30,40], [40,50,60,80]])
matrix
print(matrix.ndim)

2


In [5]:
tensor = tf.constant([[[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]]])
tensor
print(tensor.ndim)

3


### **constant()** vs **variable()**

In [6]:
var = tf.Variable([10,7])
const = tf.constant([10,7])
print(var)
print(const)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [7]:
var[0].assign(100)
print(var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,   7], dtype=int32)>


In [8]:
# const[0].assign(100)

# NameError                                 Traceback (most recent call last)
# <ipython-input-3-f1af4f6e9736> in <cell line: 1>()
# ----> 1 const[0].assign(100)

# NameError: name 'const' is not defined

### Creating Random Tensors

In [9]:
rand_1 = tf.random.Generator.from_seed(40)
rand_1 = rand_1.normal(shape=(3,4))
rand_2 = tf.random.Generator.from_seed(40)
rand_2 = rand_2.normal(shape=(3,4))

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [10]:
rand_1 = tf.random.Generator.from_seed(40)
rand_1 = rand_1.normal(shape=(3,4))
rand_2 = tf.random.Generator.from_seed(10)
rand_2 = rand_2.normal(shape=(3,4))

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.29604468, -0.21134208,  0.01063002,  1.5165398 ],
        [ 0.2730574 , -0.29925638, -0.3652325 ,  0.61883307],
        [-1.0130817 ,  0.28291714,  1.2132233 ,  0.46988967]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])>)

### Shuffling the order of the tensors

In [11]:
shuffle = tf.constant([[10,2,3], [32,34,5], [12,43,23], [22,1,21]])
tf.random.shuffle(shuffle, seed=10)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[10,  2,  3],
       [22,  1, 21],
       [32, 34,  5],
       [12, 43, 23]], dtype=int32)>

In [12]:
shuffle = tf.constant([[10,2,3], [32,34,5], [12,43,23], [22,1,21]])
tf.random.shuffle(shuffle, seed = 10)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[12, 43, 23],
       [32, 34,  5],
       [22,  1, 21],
       [10,  2,  3]], dtype=int32)>

### Setting A Global Seed

In [13]:
shuffle = tf.constant([[10,2,3], [32,34,5], [12,43,23], [22,1,21]])
tf.random.set_seed(10)
tf.random.shuffle(shuffle)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[12, 43, 23],
       [22,  1, 21],
       [10,  2,  3],
       [32, 34,  5]], dtype=int32)>

### Creating A Tensor From Numpy

In [14]:
import numpy as np
numpy_A = np.arange(1, 25)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

### Shape, Rank and Size

In [15]:
# Creating a 4 dimension tensor
random_4_T = tf.zeros(shape=(2,3,4,5))
random_4_T

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
print("Data type of tensor : ",random_4_T.shape)
print("Dimension(rank) of a tensor : ",random_4_T.ndim)
print("Datatype of tensor : ", random_4_T.dtype)
print("Total No of element in tensor : ",tf.size(random_4_T).numpy())
print("No of ele along 0th dim : ", random_4_T.shape[0])
print("No of ele along last dim : ", random_4_T.shape[-1])

Data type of tensor :  (2, 3, 4, 5)
Dimension(rank) of a tensor :  4
Datatype of tensor :  <dtype: 'float32'>
Total No of element in tensor :  120
No of ele along 0th dim :  2
No of ele along last dim :  5


### Indexing in tensors

In [17]:
random_4_T1 = tf.random.uniform(shape=(2,3,4), minval=1, maxval=20, dtype=tf.int32)
random_4_T1

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[19, 11, 15,  8],
        [18, 12, 10, 17],
        [ 7, 12, 18, 16]],

       [[18,  4, 14,  5],
        [17,  1, 18,  7],
        [ 1,  9,  8,  4]]], dtype=int32)>

In [18]:
# Extract the element at position (0, 1, 2)
n1 = random_4_T1[0,1,2]

# Extract the first row of the first matrix
n2 = random_4_T1[0,0]

# Extract the second column of the second matrix
n3 = random_4_T1[1,:,1]

# Extract the last element of each row in both matrices
n4 = random_4_T1[:,:,-1]
n1,n2,n3,n4

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([19, 11, 15,  8], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 1, 9], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 8, 17, 16],
        [ 5,  7,  4]], dtype=int32)>)

### Manipulation with tensors.(Tensors Operations)

In [19]:
random_1 = tf.constant([[1,2],[3,4]])
random_2 = tf.constant([[1,2],[3,4]])
random_1, random_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [20]:
# NOT A GLOBAL MANIPULATION
random_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [21]:
random_1 + 10

# CREATE A GLOBAL MANIPULATION
random_2 = random_2 + 10
random_1, random_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>)

In [22]:
random_1, random_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>)

In [23]:
# Using operations help to run on GPU.
tf.multiply(random_1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

### Matrix multiplication using tensorflow

**Rules:**
1.   Inner dimension must match.
2.   Output is of the outer dimension type.

**Note:**
1.   **"@"** is used for matrix multiplication in python.
2.   `tf.matmul()` or `tf.linalg.matmul()` used for matrix multiplication
3.   Generally, Tensors are represented in capital letter variables.
4.   Generally `transpose` is used over `reshape` when we want to do matrix multiplication.



In [24]:
X = tf.constant([[1,2,3],[4,5,6]])
Y = tf.constant([[3,2,1],[6,5,4]])
X.shape, Y.shape

(TensorShape([2, 3]), TensorShape([2, 3]))

In [25]:
# tf.matmul(X,Y)

In [26]:
# Changed the shape of Y for matrix multiplication using tf.reshape().

X @ tf.reshape(Y, shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 26],
       [47, 62]], dtype=int32)>

In [27]:
# Changed the shape of Y by taking the transpose of Y by using tf.transpose()

X @ tf.transpose(Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 28],
       [28, 73]], dtype=int32)>

In [28]:
# Difference in both answers because reshape and transpose are not same. Here is example of it.

Y, tf.reshape(Y, shape=(3,2)), tf.transpose(Y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 2, 1],
        [6, 5, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 2],
        [1, 6],
        [5, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 6],
        [2, 5],
        [1, 4]], dtype=int32)>)

In [29]:
# Multiplication using tf.matmul or tf.linalg.matmul

tf.linalg.matmul(a=X,b=Y,transpose_a=False, transpose_b=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 28],
       [28, 73]], dtype=int32)>

### Converting data type of Tensors

*   **Mixed precision** is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory.
[More info](https://www.tensorflow.org/guide/mixed_precision)


In [30]:
X = tf.constant([1.2,2])
X

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 2. ], dtype=float32)>

In [31]:
Y = tf.constant([1,2])
Y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [32]:
tf.cast(X,dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 2. ], dtype=float16)>

In [33]:
tf.cast(Y,dtype=tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>

### Aggregating functions

In [34]:
# Another way to create random tensor using numpy
X = tf.constant(np.random.randint(low=-50, high = 50, size=50))

Y = tf.random.uniform(shape=(50,), minval=-50, maxval=50,dtype=tf.int32)
X,Y

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([  7, -33,  49, -28,  10, -46, -19, -22,  41,   1,  21,  29,  32,
         10, -23,  -4, -39,  44, -43,   5,  -3,  -2, -14, -41, -50, -33,
        -48,  41, -48, -45, -32, -34, -19,  24,  -2,   8,  -6,   4, -23,
        -42,  -4, -19,  24, -20,   0, -36,  31,   8,  25,  48])>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([-47, -12, -40,  26, -50, -42,  20,  40,  -2,  16,  13, -15, -41,
        -50,  -1,  -2,   9,  49,  29,  18, -46,  -7,  37, -15, -15, -18,
         26,  33,  45,   4,  24,  12,  45,  -2, -47,  18, -22, -18,   2,
        -35,  22,  18,  42,  48, -12, -44,   0,  45, -12, -45], dtype=int32)>)

In [35]:
print("Value of X : ", X)
print("\n")
print("Absoulute Value of X : ", tf.abs(X))
print("\n")
print("Minimum value in X : ", tf.reduce_min(X).numpy())
print("\n")
print("Maximum value in X : ", tf.reduce_max(X).numpy())
print("\n")
print("Sum value of X : ", tf.reduce_sum(X).numpy())
print("\n")
print("Type of X : ", X.dtype)
print("\n")

# reduce_varience or reduce_std takes only floating type. So X need to typecasted
X = tf.cast(X, tf.float32)

print("Varience of X : ", tf.math.reduce_variance(X))
print("\n")
print("Standard deviation of X : ", tf.math.reduce_std(X))

Value of X :  tf.Tensor(
[  7 -33  49 -28  10 -46 -19 -22  41   1  21  29  32  10 -23  -4 -39  44
 -43   5  -3  -2 -14 -41 -50 -33 -48  41 -48 -45 -32 -34 -19  24  -2   8
  -6   4 -23 -42  -4 -19  24 -20   0 -36  31   8  25  48], shape=(50,), dtype=int64)


Absoulute Value of X :  tf.Tensor(
[ 7 33 49 28 10 46 19 22 41  1 21 29 32 10 23  4 39 44 43  5  3  2 14 41
 50 33 48 41 48 45 32 34 19 24  2  8  6  4 23 42  4 19 24 20  0 36 31  8
 25 48], shape=(50,), dtype=int64)


Minimum value in X :  -50


Maximum value in X :  49


Sum value of X :  -316


Type of X :  <dtype: 'int64'>


Varience of X :  tf.Tensor(825.5376, shape=(), dtype=float32)


Standard deviation of X :  tf.Tensor(28.73217, shape=(), dtype=float32)


In [36]:
# Posotional maxiimum and minimum of a tensor

print("Maximum element is at index : ", tf.math.argmax(X,0).numpy())
print("Minimum element is at index : ", tf.math.argmin(X,0).numpy())

Maximum element is at index :  2
Minimum element is at index :  24


In [37]:
Z = tf.random.uniform(minval=10, maxval=60,shape=(2,2,3,3),dtype=tf.int32)
Z

<tf.Tensor: shape=(2, 2, 3, 3), dtype=int32, numpy=
array([[[[37, 28, 30],
         [41, 13, 33],
         [17, 18, 37]],

        [[14, 53, 42],
         [13, 36, 19],
         [27, 47, 33]]],


       [[[45, 58, 28],
         [53, 11, 57],
         [58, 47, 45]],

        [[42, 13, 31],
         [22, 12, 41],
         [27, 41, 41]]]], dtype=int32)>

In [38]:
print("Maximum element is at index along 0th Axis : ", tf.math.argmax(Z,0).numpy())
print("Maximum element is at index along 1st Axis : ", tf.math.argmax(Z,1).numpy())
print("Maximum element is at index along 2nd Axis : ", tf.math.argmax(Z,2).numpy())
print("Maximum element is at index along 3rd Axis : ", tf.math.argmax(Z,3).numpy())

Maximum element is at index along 0th Axis :  [[[1 1 0]
  [1 0 1]
  [1 1 1]]

 [[1 0 0]
  [1 0 1]
  [0 0 1]]]
Maximum element is at index along 1st Axis :  [[[0 1 1]
  [0 1 0]
  [1 1 0]]

 [[0 0 1]
  [0 1 0]
  [0 0 0]]]
Maximum element is at index along 2nd Axis :  [[[1 0 2]
  [2 0 0]]

 [[2 0 1]
  [0 2 1]]]
Maximum element is at index along 3rd Axis :  [[[0 0 2]
  [1 1 1]]

 [[1 2 0]
  [0 2 1]]]


### Squeezing of a tensor

In [39]:
tf.random.set_seed(10)
X = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
X

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.644151  , 0.8082472 , 0.8976548 , 0.6368902 , 0.6270969 ,
           0.9936013 , 0.02359486, 0.03668392, 0.5860578 , 0.5740315 ,
           0.09047401, 0.5755553 , 0.25272822, 0.11045039, 0.61225283,
           0.1290685 , 0.89660144, 0.06479812, 0.8622047 , 0.82242084,
           0.4016037 , 0.7659943 , 0.4539342 , 0.32376182, 0.4617684 ,
           0.32858098, 0.8104389 , 0.1609515 , 0.07981062, 0.5934839 ,
           0.6243702 , 0.9112947 , 0.88744843, 0.9568223 , 0.436625  ,
           0.9997524 , 0.24064243, 0.8281152 , 0.54077435, 0.8436167 ,
           0.33806038, 0.9431902 , 0.08632314, 0.68907607, 0.53072953,
           0.9125186 , 0.06304038, 0.95265174, 0.8152896 , 0.57640743]]]]],
      dtype=float32)>

In [40]:
# Removes dimensions of size 1 from the shape of a tensor.
X = tf.squeeze(X)
X

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.644151  , 0.8082472 , 0.8976548 , 0.6368902 , 0.6270969 ,
       0.9936013 , 0.02359486, 0.03668392, 0.5860578 , 0.5740315 ,
       0.09047401, 0.5755553 , 0.25272822, 0.11045039, 0.61225283,
       0.1290685 , 0.89660144, 0.06479812, 0.8622047 , 0.82242084,
       0.4016037 , 0.7659943 , 0.4539342 , 0.32376182, 0.4617684 ,
       0.32858098, 0.8104389 , 0.1609515 , 0.07981062, 0.5934839 ,
       0.6243702 , 0.9112947 , 0.88744843, 0.9568223 , 0.436625  ,
       0.9997524 , 0.24064243, 0.8281152 , 0.54077435, 0.8436167 ,
       0.33806038, 0.9431902 , 0.08632314, 0.68907607, 0.53072953,
       0.9125186 , 0.06304038, 0.95265174, 0.8152896 , 0.57640743],
      dtype=float32)>

### One Hot Encoding

In [41]:
X = [0,1,2,3]
EncodedX = tf.one_hot(X, depth = 3)
EncodedX1 = tf.one_hot(X, depth = 4)
EncodedX2 = tf.one_hot(X, depth = 5)
EncodedX3= tf.one_hot(X, depth = 6)
EncodedX4 = tf.one_hot(X, depth = 7)
EncodedX5 = tf.one_hot(X, depth = 4,off_value="Off",on_value="On",)
EncodedX,EncodedX1,EncodedX2,EncodedX3,EncodedX4,EncodedX5

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 6), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 7), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=string, numpy=
 array([[b'On', b

### Some more mathametical functions

In [42]:
# Creating a random tensor.
X = tf.range(-10,10)
X

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9], dtype=int32)>

In [43]:
tf.square(X)

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0,   1,   4,
         9,  16,  25,  36,  49,  64,  81], dtype=int32)>

In [44]:
tf.math.square(X)

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0,   1,   4,
         9,  16,  25,  36,  49,  64,  81], dtype=int32)>

In [45]:
# Square root requires float datatype.
# Returns null for imaginary values.

tf.math.sqrt(tf.cast(X,dtype=tf.float32))

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([      nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan, 0.       , 1.       ,
       1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896, 2.6457512,
       2.828427 , 3.       ], dtype=float32)>

### Tensors and Numpy

1.   tensor -> numpy -> array or tensor <- numpy <- array (These are interconvertable in this order or reverse)
2.    Tensor created by using numpy is of `float64` type but directly created numpy is of `float32` type


In [46]:
X = tf.constant(np.array([2.,3.,4.]))
X.dtype

tf.float64

In [47]:
tf.constant([2.,3.,4.]).dtype

tf.float32

In [48]:
# Converting tensor into numpy
np.array(X)

array([2., 3., 4.])

In [49]:
X.numpy()

array([2., 3., 4.])

### Introduction python decorators (`@tf.function`)

In [50]:
def function(X, Y):
    return X + Y

X = tf.constant(tf.random.uniform(shape=(2, 3, 4), minval=10, maxval=1000))
Y = tf.constant(tf.random.uniform(shape=(2, 3, 4), minval=10, maxval=1000))

function(X, Y)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 854.12384,  968.5919 ,  819.4158 , 1147.4822 ],
        [ 657.43616, 1528.7332 ,  660.26514, 1194.2092 ],
        [ 747.9241 , 1918.3081 , 1135.6866 , 1121.7076 ]],

       [[1630.0105 , 1193.7379 ,  706.1143 , 1698.6528 ],
        [1041.681  , 1283.0791 , 1380.8301 , 1250.9628 ],
        [1498.6489 , 1532.81   ,  649.2053 ,  680.19574]]], dtype=float32)>

In [51]:
import time

@tf.function
def function(X, Y):
    return X + Y

X = tf.constant(tf.random.uniform(shape=(2, 3, 4), minval=10, maxval=1000))
Y = tf.constant(tf.random.uniform(shape=(2, 3, 4), minval=10, maxval=1000))

function(X, Y)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 848.98724,  459.02942, 1225.7688 , 1154.7202 ],
        [1316.6458 , 1447.9661 ,  585.6301 ,  842.12616],
        [1060.603  , 1150.7207 , 1016.2385 , 1198.6514 ]],

       [[ 320.27234,  712.3278 ,  700.1343 ,  852.0951 ],
        [ 989.32104,  955.4675 , 1081.94   ,  841.3914 ],
        [1158.8108 ,  647.35626, 1166.545  , 1546.8036 ]]], dtype=float32)>

### Finding access to GPUs


In [54]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [55]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]